fridge-manager/
  backend/
    __init__.py
    crud.py
    dependencies.py
    main.py
  frontend/
    static/
      favicon.ico
      staticDirectory.cpp
    templates/
      admin.html
      base.html
      cart.html
      fridge.html
      login.html
      stats.html
  requirements.txt
  Dockerfile